version: '3.9'
services:
  app:
    container_name: app
    build:
      context: ./
    depends_on:
      - cache
    ports:
      - 8081:8080
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    links:
      - cache

  cache:
    image: redis:7.0.12
    restart: always
    ports:
      - '6379:6379'
